### ISSUE TITLE
Spilled some ore?

### ISSUE THREAD

**Issue by jreach-dev** [shanemadden/factorio-logistic-cargo-wagon#4]
Hello!

When telling the train to leave, it dumped some ore on the ground that my construction robots then tried to pick up? I am all for realism and it was a good laugh :D 
![logistic_wagon_bug](https://user-images.githubusercontent.com/31992088/47307956-4de40a00-d5fe-11e8-984d-e09fa41118c3.png)

**Comment by jreach-dev** [comment]
Currently trying to isolate the conditions that cause this. Will let you know if I find anything distinctive. Seems to be on the rare side.

**Comment by shanemadden** [comment]
Yup!  That's actually intentional, kinda a "best of bad options" mechanism due to how the mod works under the hood - it happens when more cargo was delivered by robots to the wagon's logistic proxy than can actually fit in the wagon, so it can happen if two different items are requested at a station, or when there's filters on some wagon slots, etc.

Spilling them on the ground marked for deconstruction seemed like the best way to kick the items back into the logistic network - dumping the items in a temporary active provider chest, or just letting the wagon transport the invisible extra cargo which could cause confusion.

**Comment by jreach-dev** [comment]
Makes sense! Is there any way to get rid of accidentally collected coins?
